#!/bin/bash
docker run --group-add adm --net host --rm -it -v ~/book/chapter13/docker_run/pipeline/:/usr/share/logstash/pipeline -v /var/log/:/tmp/log -e xpack.monitoring.enabled=false docker.elastic.co/logstash/logstash:7.0.0 
